# Generated by Django 3.2.9 on 2021-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
