# Generated by Django 3.2.9 on 2022-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedica', '0003_paciente_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.AddField(
            model_name='paciente',
            name='servicio',
            field=models.CharField(default='', max_length=40),
        ),
    ]
